naam = input("Wat is je naam?")
aantaltickets = input("Hoeveel tickets heb je besteld?")
aantaltickets = int(aantaltickets)
prijsperticket = int("50")
email = print("Beste meneer",naam, "\nBedankt voor uw bestelling van",aantaltickets, "tickets! De totale prijs bedraagt", (prijsperticket * aantaltickets), "euro." "\nMet vriendelijke groet," "\nHet Ticketshop Team") 